package themattyboy.gadgetsngoodies.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.math.MathHelper;

public class ModelMineOSaur extends ModelBase
{
	//fields
	ModelRenderer body;
    ModelRenderer chest;
    ModelRenderer neck;
    ModelRenderer cranium;
    ModelRenderer snout;
    ModelRenderer jaw;
    ModelRenderer thigh_left;
    ModelRenderer thigh_right;
    ModelRenderer pelvis;
    ModelRenderer tail;
    ModelRenderer tail_tip;
    ModelRenderer shin_left;
    ModelRenderer shin_right;
    ModelRenderer foot_left;
    ModelRenderer foot_right;
    ModelRenderer left_left_toe;
    ModelRenderer left_middle_toe;
    ModelRenderer left_right_toe;
    ModelRenderer right_left_toe;
    ModelRenderer right_middle_toe;
    ModelRenderer right_right_toe;
    ModelRenderer upper_arm_left;
    ModelRenderer upper_arm_right;
    ModelRenderer lower_arm_left;
    ModelRenderer lower_arm_right;
    ModelRenderer left_left_finger;
    ModelRenderer left_right_finger;
    ModelRenderer right_left_finger;
    ModelRenderer right_right_finger;
    ModelRenderer front_left_tooth;
    ModelRenderer front_right_tooth;
    ModelRenderer front_middle_left_tooth;
    ModelRenderer front_middle_right_tooth;
    ModelRenderer left_tooth;
    ModelRenderer right_tooth;
  
    public ModelMineOSaur() {
    	textureWidth = 256;
    	textureHeight = 128;
    
    	body = new ModelRenderer(this, 0, 82);
    	body.addBox(-10F, 0F, 0F, 20, 16, 24);
    	body.setRotationPoint(0F, -12F, 0F);
    	body.setTextureSize(256, 128);
    	body.mirror = true;
    	setRotation(body, -0.2617994F, 0F, 0F);
    	chest = new ModelRenderer(this, 0, 50);
    	chest.addBox(-9F, 0F, -8F, 18, 16, 16);
    	chest.setRotationPoint(0F, -10F, -2F);
    	chest.setTextureSize(256, 128);
    	chest.mirror = true;
    	setRotation(chest, 0F, 0F, 0F);
    	neck = new ModelRenderer(this, 0, 28);
    	neck.addBox(-6F, 0F, -12F, 12, 10, 12);
    	neck.setRotationPoint(0F, -10F, -4F);
    	neck.setTextureSize(256, 128);
    	neck.mirror = true;
    	setRotation(neck, -0.6108652F, 0F, 0F);
    	cranium = new ModelRenderer(this, 0, 0);
    	cranium.addBox(-7F, -4F, -14F, 14, 14, 14);
    	cranium.setRotationPoint(0F, -16F, -13F);
    	cranium.setTextureSize(256, 128);
    	cranium.mirror = true;
    	setRotation(cranium, 0F, 0F, 0F);
    	snout = new ModelRenderer(this, 56, 0);
    	snout.addBox(-6F, -8F, -8F, 12, 8, 8);
    	snout.setRotationPoint(0F, -9F, -27F);
    	snout.setTextureSize(256, 128);
      	snout.mirror = true;
      	setRotation(snout, 0F, 0F, 0F);
      	jaw = new ModelRenderer(this, 96, 0);
      	jaw.addBox(-5F, 0F, -7F, 10, 2, 7);
      	jaw.setRotationPoint(0F, -9F, -27F);
      	jaw.setTextureSize(256, 128);
      	jaw.mirror = true;
      	setRotation(jaw, 0F, 0F, 0F);
      	thigh_left = new ModelRenderer(this, 224, 0);
      	thigh_left.addBox(0F, -3F, -4F, 4, 18, 12);
      	thigh_left.setRotationPoint(9F, -1F, 13F);
      	thigh_left.setTextureSize(256, 128);
      	thigh_left.mirror = true;
      	setRotation(thigh_left, -1.047198F, 0F, 0F);
      	thigh_right = new ModelRenderer(this, 192, 0);
      	thigh_right.addBox(-4F, -3F, -4F, 4, 18, 12);
      	thigh_right.setRotationPoint(-9F, -1F, 13F);
      	thigh_right.setTextureSize(256, 128);
      	thigh_right.mirror = true;
      	setRotation(thigh_right, -1.047198F, 0F, 0F);
      	pelvis = new ModelRenderer(this, 88, 100);
      	pelvis.addBox(-8F, -6F, 0F, 16, 12, 16);
      	pelvis.setRotationPoint(0F, -1F, 16F);
      	pelvis.setTextureSize(256, 128);
      	pelvis.mirror = true;
      	setRotation(pelvis, -0.5235988F, 0F, 0F);
      	tail = new ModelRenderer(this, 152, 107);
      	tail.addBox(-6F, -5F, 0F, 12, 9, 12);
      	tail.setRotationPoint(0F, 7F, 29F);
      	tail.setTextureSize(256, 128);
      	tail.mirror = true;
      	setRotation(tail, -0.3490659F, 0F, 0F);
      	tail_tip = new ModelRenderer(this, 200, 111);
      	tail_tip.addBox(-4F, -3F, 0F, 8, 7, 10);
      	tail_tip.setRotationPoint(0F, 10F, 40F);
      	tail_tip.setTextureSize(256, 128);
      	tail_tip.mirror = true;
      	setRotation(tail_tip, -0.1745329F, 0F, 0F);
      	/*shin_left = new ModelRenderer(this, 240, 30);
      	shin_left.addBox(-1.5F, 0F, 0F, 3, 11, 5);
      	shin_left.setRotationPoint(2F, 15F, 7.5F);
      	shin_left.setTextureSize(256, 128);
      	shin_left.mirror = true;
      	setRotation(shin_left, 0.9599311F, 0F, 0F);
      	shin_right = new ModelRenderer(this, 224, 30);
      	shin_right.addBox(-1.5F, 0F, 0F, 3, 11, 5);
      	shin_right.setRotationPoint(-2F, 15F, 7.5F);
      	shin_right.setTextureSize(256, 128);
      	shin_right.mirror = true;
      	setRotation(shin_right, 0.9599311F, 0F, 0F);
      	foot_left = new ModelRenderer(this, 238, 46);
      	foot_left.addBox(-3F, 0F, -2F, 6, 9, 3);
      	foot_left.setRotationPoint(0F, 11F, 4F);
      	foot_left.setTextureSize(256, 128);
      	foot_left.mirror = true;
      	setRotation(foot_left, -0.4363323F, 0F, 0F);
      	foot_right = new ModelRenderer(this, 220, 46);
      	foot_right.addBox(-3F, 0F, -2F, 6, 9, 3);
      	foot_right.setRotationPoint(-0F, 11F, 4F);
      	foot_right.setTextureSize(256, 128);
      	foot_right.mirror = true;
      	setRotation(foot_right, -0.4363323F, 0F, 0F);
      	left_left_toe = new ModelRenderer(this, 236, 58);
      	left_left_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_left_toe.setRotationPoint(2F, 8F, -3F);
      	left_left_toe.setTextureSize(256, 128);
      	left_left_toe.mirror = true;
      	setRotation(left_left_toe, 0F, -0.1745329F, 0F);
      	left_middle_toe = new ModelRenderer(this, 236, 58);
      	left_middle_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_middle_toe.setRotationPoint(0F, 8F, -4F);
      	left_middle_toe.setTextureSize(256, 128);
      	left_middle_toe.mirror = true;
      	setRotation(left_middle_toe, 0F, 0F, 0F);
      	left_right_toe = new ModelRenderer(this, 236, 58);
      	left_right_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_right_toe.setRotationPoint(-2F, 8F, -3F);
      	left_right_toe.setTextureSize(256, 128);
      	left_right_toe.mirror = true;
      	setRotation(left_right_toe, 0F, 0.1745329F, 0F);
      	right_left_toe = new ModelRenderer(this, 236, 58);
      	right_left_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_left_toe.setRotationPoint(2F, 8F, -3F);
      	right_left_toe.setTextureSize(256, 128);
      	right_left_toe.mirror = true;
      	setRotation(right_left_toe, 0F, -0.1745329F, 0F);
      	right_middle_toe = new ModelRenderer(this, 236, 58);
      	right_middle_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_middle_toe.setRotationPoint(0F, 8F, -4F);
      	right_middle_toe.setTextureSize(256, 128);
      	right_middle_toe.mirror = true;
      	setRotation(right_middle_toe, 0F, 0F, 0F);
      	right_right_toe = new ModelRenderer(this, 236, 58);
      	right_right_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_right_toe.setRotationPoint(-2F, 8F, -3F);
      	right_right_toe.setTextureSize(256, 128);
      	right_right_toe.mirror = true;
      	setRotation(right_right_toe, 0F, 0.1745329F, 0F);*/
      
      	shin_left = new ModelRenderer(this, 240, 30);
      	shin_left.addBox(-1.5F, 0F, 0F, 3, 11, 5);
      	shin_left.setRotationPoint(2F, 14.75F, 7.75F);
      	shin_left.setTextureSize(256, 128);
      	shin_left.mirror = true;
      	setRotation(shin_left, 0.9599311F, 0F, 0F);
      	shin_right = new ModelRenderer(this, 224, 30);
      	shin_right.addBox(-1.5F, 0F, 0F, 3, 11, 5);
      	shin_right.setRotationPoint(-2F, 14.75F, 7.75F);
      	shin_right.setTextureSize(256, 128);
      	shin_right.mirror = true;
      	setRotation(shin_right, 0.9599311F, 0F, 0F);
      	foot_left = new ModelRenderer(this, 238, 46);
      	foot_left.addBox(-3F, 0F, -2F, 6, 9, 3);
      	foot_left.setRotationPoint(0F, 10F, 4.75F);
      	foot_left.setTextureSize(256, 128);
      	foot_left.mirror = true;
      	setRotation(foot_left, -0.4363323F, 0F, 0F);
      	foot_right = new ModelRenderer(this, 220, 46);
      	foot_right.addBox(-3F, 0F, -2F, 6, 9, 3);
      	foot_right.setRotationPoint(0F, 10F, 4.75F);
      	foot_right.setTextureSize(256, 128);
      	foot_right.mirror = true;
      	setRotation(foot_right, -0.4363323F, 0F, 0F);
      	left_left_toe = new ModelRenderer(this, 236, 58);
      	left_left_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_left_toe.setRotationPoint(2F, 8.5F, 1F);
      	left_left_toe.setTextureSize(256, 128);
      	left_left_toe.mirror = true;
      	setRotation(left_left_toe, 0F, -0.1745329F, 0F);
      	left_middle_toe = new ModelRenderer(this, 236, 58);
      	left_middle_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_middle_toe.setRotationPoint(0F, 8.5F, 0F);
      	left_middle_toe.setTextureSize(256, 128);
      	left_middle_toe.mirror = true;
      	setRotation(left_middle_toe, 0F, 0F, 0F);
      	left_right_toe = new ModelRenderer(this, 236, 58);
      	left_right_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	left_right_toe.setRotationPoint(-2F, 8.5F, 1F);
      	left_right_toe.setTextureSize(256, 128);
      	left_right_toe.mirror = true;
      	setRotation(left_right_toe, 0F, 0.1745329F, 0F);
      	right_left_toe = new ModelRenderer(this, 236, 58);
      	right_left_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_left_toe.setRotationPoint(2F, 8.5F, 1F);
      	right_left_toe.setTextureSize(256, 128);
      	right_left_toe.mirror = true;
      	setRotation(right_left_toe, 0F, -0.1745329F, 0F);
      	right_middle_toe = new ModelRenderer(this, 236, 58);
      	right_middle_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_middle_toe.setRotationPoint(0F, 8.5F, 0F);
      	right_middle_toe.setTextureSize(256, 128);
      	right_middle_toe.mirror = true;
      	setRotation(right_middle_toe, 0F, 0F, 0F);
      	right_right_toe = new ModelRenderer(this, 236, 58);
      	right_right_toe.addBox(-1F, -1F, -8F, 2, 2, 8);
      	right_right_toe.setRotationPoint(-2F, 8.5F, 1F);
      	right_right_toe.setTextureSize(256, 128);
      	right_right_toe.mirror = true;
      	setRotation(right_right_toe, 0F, 0.1745329F, 0F);
      
      	upper_arm_left = new ModelRenderer(this, 130, 0);
      	upper_arm_left.addBox(0F, 0F, -1.5F, 2, 8, 3);
      	upper_arm_left.setRotationPoint(9F, -4F, -8F);
      	upper_arm_left.setTextureSize(256, 128);
      	upper_arm_left.mirror = true;
      	setRotation(upper_arm_left, 0.1745329F, 0F, 0F);
      	upper_arm_right = new ModelRenderer(this, 140, 0);
      	upper_arm_right.addBox(-2F, 0F, -1.5F, 2, 8, 3);
      	upper_arm_right.setRotationPoint(-9F, -4F, -8F);
      	upper_arm_right.setTextureSize(256, 128);
      	upper_arm_right.mirror = true;
      	setRotation(upper_arm_right, 0.1745329F, 0F, 0F);
      	lower_arm_left = new ModelRenderer(this, 130, 11);
      	lower_arm_left.addBox(0F, 0F, -2F, 2, 8, 2);
      	lower_arm_left.setRotationPoint(8.5F, 3.5F, -5F);
      	lower_arm_left.setTextureSize(256, 128);
      	lower_arm_left.mirror = true;
      	setRotation(lower_arm_left, -0.6981317F, 0F, 0F);
      	lower_arm_right = new ModelRenderer(this, 138, 11);
      	lower_arm_right.addBox(-2F, 0F, -2F, 2, 8, 2);
      	lower_arm_right.setRotationPoint(-8.5F, 3.5F, -5F);
  		lower_arm_right.setTextureSize(256, 128);
  		lower_arm_right.mirror = true;
  		setRotation(lower_arm_right, -0.6981317F, 0F, 0F);
  		left_left_finger = new ModelRenderer(this, 130, 21);
  		left_left_finger.addBox(0F, 0F, 0F, 1, 3, 2);
  		left_left_finger.setRotationPoint(9.5F, 8.5F, -11.5F);
      	left_left_finger.setTextureSize(256, 128);
      	left_left_finger.mirror = true;
      	setRotation(left_left_finger, 0F, 0F, -0.0872665F);
      	left_right_finger = new ModelRenderer(this, 130, 21);
      	left_right_finger.addBox(-1F, 0F, 0F, 1, 3, 2);
      	left_right_finger.setRotationPoint(9.5F, 8.5F, -11.5F);
      	left_right_finger.setTextureSize(256, 128);
      	left_right_finger.mirror = true;
      	setRotation(left_right_finger, 0F, 0F, 0.0872665F);
      	right_left_finger = new ModelRenderer(this, 130, 21);
      	right_left_finger.addBox(0F, 0F, 0F, 1, 3, 2);
      	right_left_finger.setRotationPoint(-9.5F, 8.5F, -11.5F);
      	right_left_finger.setTextureSize(256, 128);
      	right_left_finger.mirror = true;
      	setRotation(right_left_finger, 0F, 0F, -0.0872665F);
      	right_right_finger = new ModelRenderer(this, 130, 21);
      	right_right_finger.addBox(-1F, 0F, 0F, 1, 3, 2);
      	right_right_finger.setRotationPoint(-9.5F, 8.5F, -11.5F);
      	right_right_finger.setTextureSize(256, 128);
      	right_right_finger.mirror = true;
      	setRotation(right_right_finger, 0F, 0F, 0.0872665F);
      	front_left_tooth = new ModelRenderer(this, 56, 16);
      	front_left_tooth.addBox(0F, 0F, 0F, 1, 2, 1);
      	front_left_tooth.setRotationPoint(5F, -9F, -35F);
      	front_left_tooth.setTextureSize(256, 128);
      	front_left_tooth.mirror = true;
      	setRotation(front_left_tooth, 0F, 0F, 0F);
      	front_right_tooth = new ModelRenderer(this, 56, 16);
      	front_right_tooth.addBox(-1F, 0F, 0F, 1, 2, 1);
      	front_right_tooth.setRotationPoint(-5F, -9F, -35F);
      	front_right_tooth.setTextureSize(256, 128);
      	front_right_tooth.mirror = true;
      	setRotation(front_right_tooth, 0F, 0F, 0F);
      	front_middle_left_tooth = new ModelRenderer(this, 56, 16);
      	front_middle_left_tooth.addBox(0F, 0F, 0F, 1, 1, 1);
      	front_middle_left_tooth.setRotationPoint(2F, -9F, -35F);
      	front_middle_left_tooth.setTextureSize(256, 128);
      	front_middle_left_tooth.mirror = true;
      	setRotation(front_middle_left_tooth, 0F, 0F, 0F);
      	front_middle_right_tooth = new ModelRenderer(this, 56, 16);
      	front_middle_right_tooth.addBox(0F, 0F, 0F, 1, 1, 1);
      	front_middle_right_tooth.setRotationPoint(-3F, -9F, -35F);
      	front_middle_right_tooth.setTextureSize(256, 128);
      	front_middle_right_tooth.mirror = true;
      	setRotation(front_middle_right_tooth, 0F, 0F, 0F);
      	left_tooth = new ModelRenderer(this, 56, 16);
      	left_tooth.addBox(0F, 0F, 0F, 1, 1, 1);
      	left_tooth.setRotationPoint(5F, -9F, -31F);
      	left_tooth.setTextureSize(256, 128);
     	left_tooth.mirror = true;
     	setRotation(left_tooth, 0F, 0F, 0F);
     	right_tooth = new ModelRenderer(this, 56, 16);
     	right_tooth.addBox(0F, 0F, 0F, 1, 1, 1);
     	right_tooth.setRotationPoint(-6F, -9F, -31F);
     	right_tooth.setTextureSize(256, 128);
     	right_tooth.mirror = true;
     	setRotation(right_tooth, 0F, 0F, 0F);
      
     	this.thigh_left.addChild(this.shin_left);
     	this.thigh_right.addChild(this.shin_right);
     	this.shin_left.addChild(this.foot_left);
     	this.shin_right.addChild(this.foot_right);
     	this.foot_left.addChild(this.left_left_toe);
     	this.foot_left.addChild(this.left_middle_toe);
     	this.foot_left.addChild(this.left_right_toe);
     	this.foot_right.addChild(this.right_left_toe);
     	this.foot_right.addChild(this.right_middle_toe);
     	this.foot_right.addChild(this.right_right_toe);
    }
  
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
    	super.render(entity, f, f1, f2, f3, f4, f5);
    	setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    	body.render(f5);
    	chest.render(f5);
    	neck.render(f5);
    	cranium.render(f5);
    	snout.render(f5);
    	jaw.render(f5);
    	thigh_left.render(f5);
    	thigh_right.render(f5);
    	pelvis.render(f5);
    	tail.render(f5);
    	tail_tip.render(f5);
    	/*shin_left.render(f5);
    	shin_right.render(f5);
    	foot_left.render(f5);
    	foot_right.render(f5);
    	left_left_toe.render(f5);
    	left_middle_toe.render(f5);
    	left_right_toe.render(f5);
    	right_left_toe.render(f5);
    	right_middle_toe.render(f5);
   		right_right_toe.render(f5);*/
    	upper_arm_left.render(f5);
    	upper_arm_right.render(f5);
    	lower_arm_left.render(f5);
    	lower_arm_right.render(f5);
    	left_left_finger.render(f5);
    	left_right_finger.render(f5);
    	right_left_finger.render(f5);
    	right_right_finger.render(f5);
    	front_left_tooth.render(f5);
    	front_right_tooth.render(f5);
    	front_middle_left_tooth.render(f5);
    	front_middle_right_tooth.render(f5);
    	left_tooth.render(f5);
    	right_tooth.render(f5);
    }
  
    private void setRotation(ModelRenderer model, float x, float y, float z) {
    	model.rotateAngleX = x;
    	model.rotateAngleY = y;
    	model.rotateAngleZ = z;
    }
  
    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
    	super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    	this.thigh_left.rotateAngleX = MathHelper.cos(f * 0.6F) * 0.5F * f1 - 1.047198F;
    	this.thigh_right.rotateAngleX = MathHelper.cos(f * 0.6F + (float)Math.PI) * 0.5F * f1 - 1.047198F;
    
    	/*this.shin_left.rotateAngleX = -this.thigh_left.rotateAngleX * 0.5F + 1.5F;
    	this.shin_right.rotateAngleX = -this.thigh_right.rotateAngleX * 0.5F + 1.5F;
    
    	this.foot_left.rotateAngleX = -this.shin_left.rotateAngleX * 0.5F - 0.3F;
    	this.foot_right.rotateAngleX = -this.shin_right.rotateAngleX * 0.5F - 0.3F;
    
    	this.left_left_toe.rotateAngleX = -this.foot_left.rotateAngleX * 0.5F - 0.4F;
    	this.left_middle_toe.rotateAngleX = -this.foot_left.rotateAngleX * 0.5F - 0.4F;
    	this.left_right_toe.rotateAngleX = -this.foot_left.rotateAngleX * 0.5F - 0.4F;
    	this.right_left_toe.rotateAngleX = -this.foot_right.rotateAngleX * 0.5F - 0.4F;
    	this.right_middle_toe.rotateAngleX = -this.foot_right.rotateAngleX * 0.5F - 0.4F;
    	this.right_right_toe.rotateAngleX = -this.foot_right.rotateAngleX * 0.5F - 0.4F;*/
    
    	this.shin_left.rotateAngleX = -this.thigh_left.rotateAngleX + 0.9599311F;
    	this.shin_right.rotateAngleX = -this.thigh_right.rotateAngleX + 0.9599311F;
    
    	this.foot_left.rotateAngleX = -this.shin_left.rotateAngleX + 0.6F;
    	this.foot_right.rotateAngleX = -this.shin_right.rotateAngleX + 0.6F;
    	
    	this.left_left_toe.rotateAngleX = -this.foot_left.rotateAngleX - 0.4363323F * 2.1F;
    	this.left_middle_toe.rotateAngleX = -this.foot_left.rotateAngleX - 0.4363323F * 2.1F;
    	this.left_right_toe.rotateAngleX = -this.foot_left.rotateAngleX - 0.4363323F * 2.1F;
    	this.right_left_toe.rotateAngleX = -this.foot_right.rotateAngleX - 0.4363323F * 2.1F;
    	this.right_middle_toe.rotateAngleX = -this.foot_right.rotateAngleX - 0.4363323F * 2.1F;
    	this.right_right_toe.rotateAngleX = -this.foot_right.rotateAngleX - 0.4363323F * 2.1F;
  }

}
